name: UBC Workday Extension CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  check-lint-and-fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install deps
      run: yarn install --immutable
    - name: Check linting
      run: yarn run lint
    - name: Check formatting
      run: yarn run fmt
